# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Main page hero block
  icon: title
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  lead:
  background_image:
  button:
    button_link:
    button_text:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Body of the Year Bakery
  lead: "Dunedin, NZ"
  background_image: http://www.placekitten.com/1000/1000
  button: 
    button_link: /
    button_text: Contact

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
